//序章2剧情

//开始的对话
/*[0x082B] = ""
           "Corben..."
           "Hey there Shon."
           "What's up?"
           "Is everyone in the village alright?"
           "Hm? Yeah, everyone's fine."
           "What's the deal?"
           "Why shouldn't they?"
           "Oh, I'm glad."
           "You see, Magnus stopped"
           "by earlier and..."
           "What?! Magnus?"
           "Honestly?"
           "Yeah. We got into a fight."
           "I managed to defeat them,"
           "but Father wouldn't let me"
           "go with him on his journey."
           "Wait, so your dad left?"
           "...Oh, he must be thinking"
           "about the village."
           "He'd never want to endanger us."
           "That's why he isolated himself"
           "in the first place..."
           "...Corben..."
           "You want to go, right?"
           "I do. I think I can handle it,"
           "but Father doesn't see that..."
           "Still the innocent"
           "little kid, are you?"
           "You're not much older"
           "than me though, Corben..."
           "Oh? But I'm much more mature."
           "Mature enough to go with Siegfried."
           "You think so?"
           "Then why not me?"
           "I don't understand..."
           "How about this then?"
           "What? Corben,"
           "why are you...?"
           "You've still never beaten me"
           "in a sparring match, have you?"
           "So if you can finally beat me,"
           "I'll admit that you're ready to go."
           "Siegfried must plan on stopping"
           "somewhere close to get information."
           "If you hurry, you might"
           "be able to catch him."
           "Of course, you have to"
           "go through me first."
           "I-I could always just go"
           "anytime I want, you know..."
           "All alone, by your weak self,"
           "with no idea where to go?"
           "I doubt it, Shon."
           "I'm not that weak!"
           "Then stop being a coward,"
           "and show me your strength!"
           "",*/
[0x082B]	=	TXT
"\x0C\x10\x30\x01"
"\x01""Corben…\x03"
"\x01\x09\x10\x2F\x01"
"\x01嘿，Shon，"
"\x01怎么了？\x03"
"\x01\x0C"
"\x01村里的大家都还好吗？\x03"
"\x01\x09"
"\x01嗯？都好着呢。"
"\x01怎么了？\x03"
"\x01为什么会这么问？\x03"
"\x01\x0C"
"\x01噢，那就好。\x03"
"\x01如你所见，"
"\x01刚才有一队Magnus兵"
"\x01在这附近，然后…\x03"
"\x01\x09"
"\x01什么？Magnus兵？"
"\x01真的吗？\x03"
"\x01\x0C"
"\x01是的，我们打了起来，"
"\x01我设法打败了他们。\x03"
"\x01但老爸不让我"
"\x01跟他一起走。\x03"
"\x01\x09"
"\x01等一下，你老爸走了？\x03"
"\x01\x05…哦，他一定是"
"\x01为了村子着想。\x03"
"\x01他绝不会让我们陷入危险。\x03"
"\x01这就是他选择独自行动"
"\x01的原因吧…\x03"
"\x01\x0C"
"\x01…Corben…\x03"
"\x01\x09"
"\x01你想去，对吧？\x03"
"\x01\x0C"
"\x01没错，我认为我能处理好，"
"\x01可老爸他不这么想…\x03"
"\x01\x09"
"\x01你还是那个"
"\x01天真的小孩啊…\x03"
"\x01\x0C"
"\x01""Corben，"
"\x01你也好不到哪里去吧…\x03"
"\x01\x09"
"\x01哈？我可比你更成熟，"
"\x01完全有能力去帮助你父亲。\x03"
"\x01\x0C"
"\x01你是这么想的？"
"\x01为什么我不行呢？\x03"
"\x01我无法理解…\x03"
"\x01\x09\x80\x0B"
"\x01你真这么以为？\x03"
"\x01\x0C"
"\x01什么？ Corben，"
"\x01为什么你也…\x03"
"\x01\x09"
"\x01你还没有打败过我，"
"\x01不是吗？\x03"
"\x01如果你能打赢我，"
"\x01我就承认你有足够的能力。\x03"
"\x01为了获取情报，"
"\x01你父亲一定会在附近歇脚。\x03"
"\x01只要抓紧时间，"
"\x01能够追上他的。\x03"
"\x01当然，在这之前，"
"\x01你得先通过我这一关。\x03"
"\x01\x0C"
"\x01你知道…如果我想的话，"
"\x01我随时可以跑走。\x03"
"\x01\x09"
"\x01弱不禁风的你，"
"\x01独自一人能去得了哪里呢？\x03"
"\x01对吧，Shon。\x03"
"\x01\x0C"
"\x01我没有那么软弱！\x03"
"\x01\x09"
"\x01那就别做懦夫，"
"\x01向我证明你自己！\x03"N,




//开战
/*[0x082D] = ""
           "Shon, I'm not going"
           "easy on you!"
           "I-I don't want to"
           "do this, but I..."
           "I'm worried about Father..."
           "so not even you can stop me!"
           "Hah!"
           "Bring it!"
           "",*/
[0x082D]	=	TXT
"\x0A\x10\x2F\x01"
"\x01Shon，我不会"
"\x01手下留情的！\x03\x11"
"\x01\x0B\x10\x30\x01"
"\x01我…我不想这么做，"
"\x01但我…\x03"
"\x01我担心我的父亲，"
"\x01即使是你也不能阻止我！\x03\x11"
"\x01\x0A\x10\x2F\x01"
"\x01哈哈！"
"\x01接招吧！\x03"N,


//打赢后
/*[0x082E] = ""
           "Unh..."
           "Not bad..."
           "",*/
[0x082E]	=	TXT
"\x0A\x10\x2F\x01"
"\x01呃…"
"\x01不赖嘛…\x03"N,


//结束后对话
/*[0x082C] = ""
           "Hah... hah..."
           "Ouch... you got me, Shon."
           "I can't believe I lost..."
           "Me neither..."
           "Are you alright?"
           "Talking down on me already?"
           "I'm fine."
           "Come on Shon, let's hurry up."
           "Do you know which way your"
           "Dad went when he left?"
           "South."
           "Then... he'll likely stop"
           "at Anura. Let's go."
           "W-wait!"
           "What? Don't you want"
           "to help your Dad?"
           "T-Thanks."
           "Don't mention it."
           "",*/
[0x082C]	=	TXT
"\x0C\x10\x30\x01"
"\x01呼…呼…\x03"
"\x01\x09\x10\x2F\x01"
"\x01啊…真不敢相信"
"\x01你打败了我，Shon。\x03"
"\x01\x0C"
"\x01我也是…"
"\x01你没事吧？\x03"
"\x01\x09"
"\x01我没事，"
"\x01别瞧不起我。\x03"
"\x01快来吧，别磨蹭了。\x03"
"\x01你知道你父亲"
"\x01从哪边走的吗？\x03"
"\x01\x0C"
"\x01南边。\x03"
"\x01\x09"
"\x01那…他可能在Anura,"
"\x01我们走吧。\x03"
"\x01\x0C"
"\x01等…等等…\x03"
"\x01\x09"
"\x01怎么？你不想"
"\x01帮助你父亲么？\x03"
"\x01\x0C"
"\x01谢谢你…\x03"
"\x01\x09"
"\x01小事一桩。\x03"
"\x01"N,