//第一章

//开始前对话
/*[0x0834] = ""
           "Ah..."
           "It's so quiet here..."
           "The people here seem so uninterested"
           "in Magnus's war against everyone else."
           "They haven't even set up"
           "a basic perimeter defense!"
           "And it's only a matter of time"
           "before their soldiers arrive here."
           "Of course, sir."
           "Anura is no militant area,"
           "just a small farming and trade town."
           "There's no reason to"
           "have an army."
           "No one would come"
           "here for anything."
           "The war doesn't affect us"
           "commoners and farmers."
           "That is wrong."
           "Magnian soldiers quickly take"
           "over \"peaceful\" areas like here"
           "and force tributes on every citizen."
           "It's only a matter of time."
           "If not appeased, they will kill many..."
           "men, women, and children alike!"
           "Do you think that, even for"
           "a moment, you're safe?"
           "Haha, rumors and lies"
           "abound, I'll say."
           "You speak of them as if"
           "though they are savages."
           "But the past Holy Emperor of Magnus"
           "was a benevolent ruler,"
           "and helped us Atheyans by mediating"
           "our tribal conflicts many times!"
           "His son wouldn't ruin such"
           "a legacy with cruelty."
           "I'm no politician, but there"
           "must be a reason to all of this."
           "Gah... How I wish there was"
           "a reason, and that I knew it!"
           "Regardless, the Magnian Empire"
           "may be preoccupied now,"
           "but that won't last long!"
           "You'll regret such thoughts!"
           "",*/
[0x0834]	=	TXT
"\x0C\x10\x16\x01"
"\x01""啊…"
"\x01""好宁静…\x03"
"\x01""这里的人们似乎并不在意"
"\x01""这场由Magnus挑起的战争。\x03"
"\x01""他们甚至没有采取"
"\x01""任何防御措施！\x03"
"\x01""战争波及到这里"
"\x01""只是时间问题。\x03"
"\x01""\x08\x10\xAB\x01""不是的，先生。\x1F\x03"
"\x01""Anura不是军事重镇，"
"\x01""只是一座小型农贸城镇。\x03"
"\x01""军队没有理由来这里的。\x03"
"\x01""这里没有"
"\x01""他们想要的东西。\x03"
"\x01""战争不会影响我们"
"\x01""这些平民百姓的。\x03"
"\x01""\x0C不，你错了。\x03"
"\x01""Magnus军队很快就会占领"
"\x01""像这里一样的\"祥和之地\"，\x03"
"\x01""并强迫每个人交纳贡品，"
"\x01""这只是时间问题。\x03"
"\x01""如果不服从，"
"\x01""他们便会屠杀村民，"
"\x01""即使是小孩也不会放过！\x1F\x03"
"\x01""你真觉得你们还有机会"
"\x01""享受这片刻的宁静吗？\x03"
"\x01""\x08"
"\x01""哈哈哈，\x1F"
"\x01""这不过是谣言罢了。\x1F\x03"
"\x01""你口中的他们"
"\x01""就像是野蛮人一样，\x03"
"\x01""但前任Magnus皇帝Holy，"
"\x01""是一名仁慈的统治者。\x03"
"\x01""他好几次调解我们部落间的冲突，"
"\x01""帮了我们Atheya人大忙！\x03"
"\x01""他的儿子自然不会"
"\x01""毁了这样的名声。\x03"
"\x01""我不是政治家，"
"\x01""但现在这一切"
"\x01""一定都有一个合理的理由的。\x03"
"\x01""\x0C"
"\x01""呵…"
"\x01""我也多么希望有个理由\x03"
"\x01""无论如何，"
"\x01""现在Magnus帝国"
"\x01""可能无暇顾及这里\x03"
"\x01""但这和平不会持续很久，"
"\x01""你会为你的想法后悔的！\x03"N,


//第二段
/*[0x0BE5] = ""
           "Hm?"
           "I hear something..."
           "",*/
[0x0BE5]	=	TXT
"\x09\x10\x16\x01"
"\x01""嗯？"
"\x01""那是什么声音…\x03"N,


//第三段
/*[0x0835] = ""
           "Father!"
           "There you are!"
           "Shon?"
           "That can't be..."
           "You... urgh!"
           "Shon, dammit!"
           "Why are you here? Why did"
           "you run off from the village?!"
           "Father, I... was worried..."
           "I-I brought Corben with me too!"
           "With the both of us here,"
           "we can be useful to you!"
           "You brought another into this?"
           "You could have gotten killed,"
           "along with Corben,"
           "for your own selfish reasons."
           "A knight thinks before he acts,"
           "Shon! Do at least that much!"
           "I promised your Mother I'd keep"
           "you safe, and you're making it hard!"
           "I... I'm not a little boy anymore."
           "I know how to protect myself!"
           "Ah..."
           "If you were truly ready,"
           "I would have told you to come."
           "Sir, I..."
           "came of my own accord."
           "I couldn't let Shon"
           "run off alone."
           "He's really only"
           "concerned about you."
           "......"
           "......"
           "Sigh..."
           "Well, don't cause"
           "too much trouble."
           "You stay by and actually"
           "listen to me, got that?"
           "We're too far to head back"
           "to the village anyway..."
           "Those Magnian dastards are likely to up"
           "the level of their pursuit of me as well."
           "Even now, they might have"
           "tracked you to this location..."
           "I'm sorry, Father..."
           "But I promise, Corben and I"
           "won't let you down!"
           "...I won't, huh?"
           "Thanks for speaking for me, Shon..."
           "",*/
[0x0835]	=	TXT
"\x0B\x10\x30\x01"
"\x01""\x08\x10\x16\x01\x80\x0B"
"\x01""\x0B"
"\x01""父亲！\x1F"
"\x01""找到你了！\x03"
"\x01""\x09Shon？\x1F"
"\x01""你不是…\x03"
"\x01""你…呃"
"\x01""Shon，该死！\x1F\x03"
"\x01""你怎么在这里！"
"\x01""为什么要离开村子？！\x03"
"\x01""\x0B"
"\x01""父亲，我…我很担心…"
"\x01""我是和Corben一起来的！\x03"
"\x01""我们俩不会连累你的！\x03"
"\x01""\x09"
"\x01""你们俩？\x03"
"\x01""因为你自私的想法，"
"\x01""你们可能都会死！\x03"
"\x01""Shon，一个真正的骑士"
"\x01""要学会三思而后行！\x03"
"\x01""我向你母亲发誓保证你的安全，"
"\x01""你这是在为难我啊！\x03"
"\x01""\x0B"
"\x01""我…我已经不是小孩子了，"
"\x01""我懂得如何保护自己！\x03"
"\x01""\x0D\x10\x2F\x01"
"\x01""呃…\x03"
"\x01""\x09"
"\x01""如果你真的长大了，"
"\x01""我自然会让你跟来。\x03"
"\x01""\x0D"
"\x01""我是自愿来的，\x03"
"\x01""我不能让Shon"
"\x01""独自前来，\x03"
"\x01""他真的只是"
"\x01""担心你而已。\x03"
"\x01""\x09\x80\x1D\x16……"
"\x01""……\x03\x16"
"\x01""好吧…\x1F"
"\x01""\x80\x1C\x05\x05记住，\x1F"
"\x01""不要去惹麻烦。\x1F\x03"
"\x01""你要听我的，"
"\x01""明白吗？\x1F\x03"
"\x01""不管怎么说，"
"\x01""我们离村子都太远了…\x03"
"\x01""那些Magnus的混蛋可能会"
"\x01""加紧对我的追杀。\x03"
"\x01""现在，他们可能追踪你，"
"\x01""而找到这里。\x03\x11"
"\x01""\x0B"
"\x01""抱歉，父亲…\x03"
"\x01""但是我保证，"
"\x01""我和Corben不会让你失望的！\x03\x11"
"\x01""\x0D"
"\x01""…是嘛"
"\x01""谢谢你，Shon…\x03"N,

//第四段
/*[0x0836] = ""
           "Eh, boss, this is"
           "the town you wanted."
           "Geh heh heh..."
           "Anura, a small trading town"
           "with no accursed militia."
           "Who knows what we'll"
           "be able to take?"
           "I'm surprised no one's gotten"
           "to a village this ripe yet!"
           "Gold, furs, maybe some"
           "of'em Atheyan beauties."
           "Quiet, grunt!"
           "You can daydream"
           "after you're done!"
           "Kill anyone who resists first,"
           "then go do the usual thing!"
           "And the Atheyan beauties?"
           "Yar har har!"
           "Are you dumb?"
           "Of course we'll take"
           "them lucky charms!"
           "Heh..."
           "Sure thing, boss."
           "Bahahaha!"
           "When you have power AND brains,"
           "you become unstoppable! Like me!"
           "",*/
[0x0836]	=	TXT
"\x09\x10\x89\x01\x0C\x10\xBC\x01首领，这就是\x1F"
"\x01""你找的城镇。\x03"
"\x01""\x09哼哼哼…\x03"
"\x01""Anura，一个"
"\x01""没有民兵的小城镇。\x03"
"\x01""让我们看看能从这"
"\x01""搜刮到什么东西。\x03"
"\x01""真是没有想到，"
"\x01""这里竟然没被捷足先登。\x03"
"\x01""\x0C"
"\x01""黄金、毛皮，"
"\x01""还有Atheya美人…\x03"
"\x01""\x09闭嘴！臭小子，\x03"
"\x01""做到之后"
"\x01""再扯这些吧！\x03"
"\x01""把胆敢反抗的都杀了，"
"\x01""然后把有用的东西都抢走！\x03"
"\x01""\x0C"
"\x01""那Atheya美人呢？"
"\x01""啊哈哈哈\x03"
"\x01""\x09你这个笨蛋！\x1F"
"\x01""自然是给她们"
"\x01""带来\"好运\"了！\x03"
"\x01""\x0C嘿嘿…"
"\x01""了解了，首领。\x1F\x03"
"\x01""\x11"
"\x01""\x09"
"\x01""啊哈哈哈！\x03"
"\x01""如我一般智勇双全的人，"
"\x01""是势不可挡的！\x03"N,


//第五段
/*[0x0837] = ""
           "...Well look who it is..."
           "Bandits!"
           "They've attacked and are"
           "stealing everything!"
           "Including the ladies!"
           "...See what I mean?"
           "This is exactly what"
           "Magnians will do to here."
           "Savages!"
           "Beasts!"
           "It's a miracle I got out"
           "of there in one piece!"
           "And there's no way I'm"
           "staying anywhere near here!"
           "Father, we have to fight"
           "off these bandits!"
           "We have to help the villagers!"
           "You've only just had"
           "your first real fight,"
           "and yet you want to rush in and"
           "save some foolish villagers?"
           "Well, wouldn't the villagers be in"
           "our debt if we fight off this threat?"
           "And more importantly, isn't a knight"
           "supposed to protect the people?"
           "I suppose you're right..."
           "It could in fact be a stroke of good luck"
           "coming our way, if we handle it right."
           "Alright, Shon, Corben..."
           "Our enemies may be mountain bandits,"
           "but let's not underestimate them."
           "We do battle!"
           "",*/
[0x0837]	=	TXT
"\x0D\x10\x30\x01\x0B\x10\x16\x01…是谁…\x03"
"\x01""\x08\x10\xAB\x01\x80\x0B"
"\x01""山贼！"
"\x01""\x80\x0B他们袭击了镇子，"
"\x01""夺走了一切！\x03"
"\x01""\x80\x0B连女人都不放过！\x1F\x03"
"\x01""\x0B"
"\x01""…看吧，\x03"
"\x01""这正是Magnus"
"\x01""将要做的。\x03"
"\x01""\x09\x80\x0B畜生！"
"\x01""\x80\x0B禽兽！\x03"
"\x01""我能逃出来"
"\x01""真是一个奇迹！\x03"
"\x01""这附近已经没有"
"\x01""能待的地方了！\x03"
"\x01""\x11\x0D"
"\x01""父亲，我们得\x1F"
"\x01""打败这些山贼，\x03"
"\x01""我们必须帮助镇民们。\x03"
"\x01""\x0B\x11\x0A\x10\x16\x01"
"\x01""你才刚经历严格意义上的"
"\x01""第一场战斗，\x03"
"\x01""你想冲进去"
"\x01""救这些愚蠢的镇民？\x03"
"\x01""\x0D\x80\x0E"
"\x01""是的，如果我们打败山贼，"
"\x01""他们会给我们帮助的。\x03"
"\x01""更重要的是，"
"\x01""骑士不应该保护人民吗？\x03"
"\x01""\x0A"
"\x01""的确如此…\x03"
"\x01""如果我们处理得当，"
"\x01""这未尝不是一件好事。\x03"
"\x01""Shon，Corben，\x03"
"\x01""敌人虽然只是山贼，"
"\x01""但绝不能掉以轻心。\x03"
"\x01""上吧！\x03"N,


//第二回合
/*[0x082F] = ""
           "There he is..."
           "The former Knight Commander"
           "of Regalia, Sir Siegfried..."
           "But there's bandits too..."
           "I can't arrest him like this..."
           "I guess I'll leave the safety"
           "of the village to him..."
           "Wonder what I'll"
           "tell the General..."
           "",*/
[0x082F]	=	TXT
"\x0C\x10\x27\x01"
"\x01""他在这里…\x03"
"\x01""Regalia的前骑士军将，"
"\x01""Siegfried长官…\x03"
"\x01""但这里有山贼出没…"
"\x01""我不能在这时候逮捕他…\x03"
"\x01""我想我还是把镇子的安全"
"\x01""交给他吧…\x03"
"\x01""不知道该怎么"
"\x01""向将军汇报呢…\x03"N,



//boss开战
/*[0x0872] = ""
           "Ah har har!"
           "Brains and power!"
           "You got none!"
           "",*/
[0x0872]	=	TXT
"\x10\x89\x01"
"\x01""啊哈哈！\x1F"
"\x01""头脑与力量！\x1F"
"\x01""你一样都没有！\x1F\x03"N,


//击败boss后
/*[0x0873] = ""
           "Gah..."
           "Damn, nothing is mine now..."
           "The Atheyan beauties..."
           "We'll get you for this..."
           "",*/
[0x0873]	=	TXT
"\x10\x89\x01"
"\x01""呃…"
"\x01""可恶，什么都没得到…\x03"
"\x01""Atheya美人…"
"\x01""你会付出代价的…\x03"N,


//章节结束
/*[0x0838] = ""
           "Thank you, brave warriors!"
           "You have saved us all!"
           "Father, we have to hurry."
           "It looks like some of the"
           "bandits were able to retreat."
           "They're not bothering us."
           "Well, not anymore."
           "Let's just leave them."
           "Nonsense."
           "You've proved that we"
           "cannot survive defenseless."
           "We'll train some militia"
           "and take them ourselves."
           "You guys are rebels, correct?"
           "Or am I mistaken?"
           "You are correct."
           "Well, we may be a small area now, but"
           "our spirits are with the rebellion."
           "It's in the interests of our"
           "trade and our safety, after all."
           "We are in great debt"
           "to you, Sir..."
           "Sir Siegfried."
           "Ah, Sir Siegfried."
           "Again, thank you."
           "Now, if you'll excuse me..."
           "It seems like everything"
           "has worked out alright."
           "We saved a town and gained some"
           "support for the cause of liberation."
           "But we're also putting ourselves"
           "back on the map, as well..."
           "What do you mean by that?"
           "Remember how when you were young,"
           "we ran away from Valencia?"
           "Well, Magnus was still"
           "keeping an eye out for me."
           "But now word will get out that"
           "we're fighting Magnus,"
           "even if it's only as few as"
           "three people."
           "The Empire won't give anyone"
           "a chance to disrupt their plans."
           "So my point is, they're"
           "going to start hunting us..."
           "Which is ultimately why I"
           "didn't want you to come."
           "But... if we didn't, we couldn't"
           "have saved Anura, right?"
           "Hah! My injury is still a little sore"
           "but these bandits are nothing."
           "Now that you're here though,"
           "I don't have much of a choice"
           "but to keep you"
           "around for a while."
           "If you decide to disobey your father,"
           "your punishment will be dealt by Magnus."
           "They are a bit more"
           "painful than I could be."
           "I will, father!"
           "What about you, Corben?"
           "Are you going to stay?"
           "Of course. I'm staying even"
           "if you kick me out."
           "Is that so?"
           "Well, you're definitely a"
           "talented young rider."
           "Help me keep watch over"
           "Shon, alright?"
           "Of course, Sir."
           "",*/
[0x0838]	=	TXT
"\x0B\x10\x16\x01\x09\x10\xAB\x01"
"\x01""勇士，非常感谢"
"\x01""你们救了我们！\x03"
"\x01""\x0C\x10\x30\x01"
"\x01""父亲，我们得快点了。\x03"
"\x01""看起来这些山贼\x1F"
"\x01""开始撤退了。\x1F\x03"
"\x01""\x0D\x10\x2F\x01"
"\x01""他们已经不足以\x1F"
"\x01""\x05\x05\x05\x05\x05构成威胁了。\x03"
"\x01""我们该走了。\x03"
"\x01""\x09不不不，\x1F\x03"
"\x01""你是对的，\x1F"
"\x01""我们必须要加以防备。\x1F\x03"
"\x01""我们会训练一些民兵，"
"\x01""由他们来保护镇子。\x03"
"\x01""你们是反抗者，对吧？"
"\x01""或我猜错了？\x03"
"\x01""\x0B"
"\x01""你是对的。\x03"
"\x01""\x09"
"\x01""嗯，也许这只是一个小地方，"
"\x01""但我们也想反抗Magnus。\x03"
"\x01""毕竟，这事关"
"\x01""我们的贸易和安全。\x03"
"\x01""我们欠你们一个很大的人情，"
"\x01""该怎么称呼您？\x03"
"\x01""\x0B"
"\x01""Siegfried。\x03"
"\x01""\x09"
"\x01""Siegfried先生，"
"\x01""再次感谢你们。\x03"
"\x01""我就先离开了…\x03"
"\x01""\x11\x0C\x11\x0A\x10\x30\x01"
"\x01""\x0B"
"\x01""看起来，"
"\x01""事情已经顺利解决了。\x03"
"\x01""我们救了一个小镇，"
"\x01""也为反抗运动取得了一些支持。\x03"
"\x01""但是与此同时，"
"\x01""我们的位置也暴露了。\x03"
"\x01""\x0A"
"\x01""什么意思？\x03"
"\x01""\x0B"
"\x01""还记得你小时候，"
"\x01""我们从Valencia逃跑的事吗？\x03"
"\x01""Magnus仍然"
"\x01""一直在监视我。\x03"
"\x01""现在我们和Magnus开战的"
"\x01""消息会传出去，\x03"
"\x01""虽然我们"
"\x01""只有三个人。\x03"
"\x01""帝国是不会给任何人，"
"\x01""扰乱他们计划的机会的。\x03"
"\x01""我想说的是，"
"\x01""他们会开始追捕我们，\x03"
"\x01""这也正是我不让你来"
"\x01""的根本原因。\x03"
"\x01""\x0A"
"\x01""但是…如果没有我们，"
"\x01""Anura不会得到援救，对吧？\x03"
"\x01""\x0B"
"\x01""哈哈！我的伤口仍旧隐隐作痛，"
"\x01""但这些山贼连命都没有了。\x03"
"\x01""既然你们已经来了，"
"\x01""我别无选择。\x03"
"\x01""但这段时间"
"\x01""你得听我的。\x1F\x03"
"\x01""不然，\x1F"
"\x01""Magnus是不会对你仁慈的。\x1F\x03"
"\x01""他们下手\x1F"
"\x01""可要比我狠毒。\x03"
"\x01""\x0A"
"\x01""明白了，父亲。\x11"
"\x01""\x0D\x11\x0A\x10\x2F\x01"
"\x01""\x0B"
"\x01""Corben，你呢？"
"\x01""你要一起来吗？\x03"
"\x01""\x0A"
"\x01""当然，即使你赶我走，"
"\x01""我也会留下来的。\x03"
"\x01""\x0B"
"\x01""是吗？\x03"
"\x01""嗯，毫无疑问你是一个"
"\x01""天资聪慧的年轻骑士。\x03"
"\x01""帮我看着点Shon，"
"\x01""好吗？\x03"
"\x01""\x0A"
"\x01""好的。\x03"N,


//军营
/*[0x0839] = ""
           "So Kevin, you have lost Siegfried?"
           "Yes, General Howard."
           "He had a skirmish with some bandits,"
           "and I thought it best not to intervene..."
           "I am ready to receive any"
           "punishment for my actions."
           "I see..."
           "Well then..."
           "I am relocating you"
           "to Garnia Fortress."
           "Some of the Gorn nomads have betrayed"
           "their people in order to side with Magnus."
           "They have captured the fort and are"
           "requesting Magnian aid in guarding it."
           "You are to take your men and"
           "help them guard the fortress,"
           "in the case that Siegfried or"
           "anybody else attempts to take it back."
           "Consider this reassignment your"
           "punishment, Kevin."
           "Yes, sir..."
           "...I hope I don't mess"
           "this one up..."
           "",*/
[0x0839]	=	TXT
"\x09\x10\x27\x01\x0C\x10\x47\x01那么Kevin，你没抓到Siegfried？\x03"
"\x01""\x09是的，Howard将军。\x03"
"\x01""他正在与山贼们交手，"
"\x01""我觉得最好不要介入其中…\x03"
"\x01""我已经准备好\x1F"
"\x01""为我的行为受罚了。\x03"
"\x01""\x0C"
"\x01""嗯…"
"\x01""那么…\x03"
"\x01""我要把你"
"\x01""调到Garnia要塞。\x1F\x03"
"\x01""Gorn部落的一部分人"
"\x01""投靠了Mangus，\x1F\x03"
"\x01""他们压制了要塞，"
"\x01""并请求Mangus帮他们看守。\x1F\x03"
"\x01""你带一些人去帮他们"
"\x01""看守要塞，\x1F\x03"
"\x01""确保Siegfried或者任何其他人"
"\x01""不会夺回它。\x03"
"\x01""就把这当作是"
"\x01""对你的惩罚吧。\x03"
"\x01""\x09是，长官…\x03"
"\x01""\x0C\x11\x09"
"\x01""…希望这一次，"
"\x01""我不会再搞砸了…\x03"N,